---
lessonName: Using Jinja for Configuration Templates
lessonId: 16
category: introductory
tier: prod
prereqs:
  - 14  # YAML

utilities:
- name: linux1
  image: antidotelabs/utility

stages:
  - id: 1
    description: Introduction
  - id: 2
    description: For Loops
  - id: 3
    description: '"If" and "Set" Statements'
  - id: 4
    description: Passing Data into a Template From YAML
  - id: 5
    description: Importing a Jinja Template from a File
