---
lessonName: Automating the Troubleshooting Chain
lessonID: 21
category: troubleshooting
lessondiagram: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-21/lessondiagram.png
topologyType: custom

blackboxes:
- name: asterisk
  image: antidotelabs/asterisk
  ports: [8088]
- name: sipphone
  image: pjsua-lindsey
  ports: [25]   # TODO(mierdin): since blackboxes have no implicit ports added, we have to add one here or the service creation will break. Should
                # make it so that syringe doesn't require services are created. Should skip this for black boxes, and also make sure it's not required during
                # livelab conversion.

utilities:
- name: linux1
  image: antidotelabs/utility
  sshuser: root
  sshpassword: antidotepassword

devices:
- name: vqfx1
  image: antidotelabs/vqfxspeedy
  sshuser: root
  sshpassword: VR-netlab9
- name: vqfx2
  image: antidotelabs/vqfxspeedy
  sshuser: root
  sshpassword: VR-netlab9
- name: vqfx3
  image: antidotelabs/vqfxspeedy
  sshuser: root
  sshpassword: VR-netlab9

connections:
- a: vqfx1
  b: vqfx2
  subnet: 10.0.10.0/24
- a: vqfx2
  b: vqfx3
  subnet: 10.23.0.0/24
- a: vqfx3
  b: vqfx1
  subnet: 10.31.0.0/24
- a: vqfx2
  b: sipphone
  subnet: 10.10.200.0/24
- a: vqfx1
  b: asterisk
  subnet: 10.10.100.0/24

stages:
  1:
    description: Get the IP Address for a Phone Extension
    labguide: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-21/stage1/guide.md
    configs:
      vqfx1: stage1/configs/vqfx1.txt
      vqfx2: stage1/configs/vqfx2.txt
