---
hosts:
  - device: vqfx1-svc
    username : root
    passwd: VR-netlab9
    port: 22
  - device: vqfx2-svc
    username : root
    passwd: VR-netlab9
    port: 22
  - device: vqfx3-svc
    username : root
    passwd: VR-netlab9
    port: 22
tests:
    - jsnapy_tests.yaml