---
lessonName: Network Unit Testing with JSNAPY
lessonId: 12
category: verification
lessondiagram: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-12/lessondiagram.png
topologyType: custom
tier: prod

utilities:
- name: linux1
  image: antidotelabs/utility

devices:
- name: vqfx1
  image: antidotelabs/vqfx:snap1
- name: vqfx2
  image: antidotelabs/vqfx:snap2
- name: vqfx3
  image: antidotelabs/vqfx:snap3

connections:
- a: vqfx1
  b: vqfx2
  subnet: 10.12.0.0/24
- a: vqfx2
  b: vqfx3
  subnet: 10.23.0.0/24
- a: vqfx3
  b: vqfx1
  subnet: 10.31.0.0/24
- a: vqfx1
  b: linux1
  subnet: 10.1.0.0/24

stages:
  - id: 1
    description: No BGP config - tests fail
    labGuide: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-12/stage1/guide.md

  - id: 2
    description: Correct BGP config - tests pass
    labGuide: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-12/stage2/guide.md
