---
apiVersion: v1
kind: Pod
metadata:
  name: bb2
  labels:
      antidote_lab: "1"
      lab_instance: "1"
      podname: "bb2"
  annotations:
      k8s.v1.cni.cncf.io/networks: '[
              { "name": "12-net" },
              { "name": "23-net" },
              { "name": "31-net" }
      ]'
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - "3600"
    ports:
      - containerPort: 22
      - containerPort: 830
