---
lessonName: Junos Automation with PyEZ
lessonId: 24
category: configuration
tier: prod
juniperSpecific: true

utilities:
- name: linux
  image: antidotelabs/utility

devices:
- name: vqfx
  image: antidotelabs/vqfx:snap1
  ports: [830]

connections:
- a: vqfx
  b: linux
  subnet: 10.1.0.0/24

stages:
  - id: 1
    description: Introduction

  - id: 2
    description: Collect Data from Junos Devices

  - id: 3
    description: Parse Information

  - id: 4
    description: Configuration Management

  - id: 5
    description: PyEZ Tables and Views
