---
apiVersion: v1
kind: Pod
metadata:
  name: grafana
  labels:
    app: grafana
    antidote_role: infra
spec:
  containers:
  - name: grafana
    # http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
    image: grafana/grafana:5.0.0
    imagePullPolicy: Always
    ports:
    - containerPort: 3000
    volumeMounts:
    - mountPath: "/var/lib/grafana"
      name: grafanadata
    env:

    # Grafana is kind of a pain in the ass when you change this. It doesn't work for all paths. So you have to do this and still
    # rewrite to "/" in the ingress.
    - name: GF_SERVER_ROOT_URL
      value: "https://labs.networkreliability.engineering/grafana"
    - name: GF_SECURITY_ADMIN_USER
      value: "mierdin"
    - name: GF_SECURITY_ADMIN_PASSWORD
      value: "nrelabs"
  volumes:
    - name: grafanadata
      persistentVolumeClaim:
        claimName: grafana-pvc

---
kind: Service
apiVersion: v1
metadata:
  name: grafana
  namespace: default
spec:
  selector:
    app: grafana
  ports:
    - name: web
      port: 3000
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    app: grafana
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs: 
    path: /antidotepersist/grafanadata
    server: "10.55.112.186"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "" # the storageClassName has to be specified
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: grafana

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
  name: grafana
  namespace: default
spec:
  tls:
    - hosts:
      - labs.networkreliability.engineering
      secretName: tls-certificate
  rules:
  - host: labs.networkreliability.engineering
    http:
      paths:
      - path: /grafana
        backend:
          serviceName: grafana
          servicePort: 3000
