---
lessonName: STIG Compliance Validation
lessonId: 12
category: workflows
lessonDiagram: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-32/lessondiagram.png
tier: prod
prereqs:
  - 13  # NAPALM
  - 12  # JSNAPy
description: Security Technical Implementation Guides (STIGs) are the configuration standards for United States Department of Defense (DoD) infrastructure. Any network engineer that has experience in running any part of these systems has had to spent countless hours going over infrastructure elements and ensuring they're compliant with these standards. In this lesson, we'll explore two appraoches for automating STIG compliance checks, and saving countless hours of manual data-gathering.
slug: STIG
tags:
- jsnapy
- napalm
- stig

utilities:
- name: linux1
  image: antidotelabs/utility

devices:
- name: vqfx1
  image: antidotelabs/vqfx:snap1
- name: vqfx2
  image: antidotelabs/vqfx:snap2
- name: vqfx3
  image: antidotelabs/vqfx:snap3

connections:
- a: vqfx1
  b: vqfx2
  subnet: 10.12.0.0/24
- a: vqfx2
  b: vqfx3
  subnet: 10.23.0.0/24
- a: vqfx3
  b: vqfx1
  subnet: 10.31.0.0/24

stages:
  - id: 1
    description: STIG Compliance Validation with NAPALM
Security Technical Implementation Guides (STIGs) are the configuration standards for DOD IA and IA-enabled devices/systems
  - id: 2
    description: STIG Compliance Validation with JSNAPy
