---
lessonName: Terraform & Junos
lessonId: 31
category: tools
lessonDiagram: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-31/lessondiagram.png
description: Terraform provides a declarative way of managing resources and now you can experiment with controlling Junos resources through this exciting lesson! 
tier: prod
slug: Terraform
tags:
  - terraform
  - declarative
  - junos

utilities:
- name: terraform1
  image: davidjohngee/junos-qfx-terraform:v0.11.11

devices:
- name: vqfx1
  image: antidotelabs/vqfx:snap1
- name: vqfx2
  image: antidotelabs/vqfx:snap2
- name: vqfx3
  image: antidotelabs/vqfx:snap3

connections:
- a: vqfx1
  b: vqfx2
  subnet: 10.12.0.0/24
- a: vqfx2
  b: vqfx3
  subnet: 10.23.0.0/24
- a: vqfx3
  b: vqfx1
  subnet: 10.31.0.0/24

stages:
  - id: 1
    description: Terraform Init

  - id: 2
    description: Terraform Plan 

  - id: 3
    description: Terraform Apply

  - id: 4
    description: Terraform Destroy

  - id: 5
    description: Terraform Bonus
