---
apiVersion: v1
kind: Pod
metadata:
  name: csrx1
  # namespace: lesson1-abcdef
  labels:
    antidote_lab: "1"
    lab_instance: "1"
    podname: "csrx1"
  annotations:
    networks: '[
        { "name": "weave-mgmt" },
        { "name": "weave-12" },
        { "name": "weave-31" }
    ]'
spec:
  containers:
  - name: csrx1
    image: csrx:18.1R1.9
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
    env:
    - name: CSRX_ROOT_PASSWORD
      value: Password1!
    ports:
    - containerPort: 22
    - containerPort: 830

---
kind: Service
apiVersion: v1
metadata:
  name: csrx1-service
spec:
  selector:
    antidote_lab: "1"
    lab_instance: "1"
    podname: "csrx1"
  ports:
    - name: ssh
      port: 22
      targetPort: 22
    - name: netconf
      port: 830
      targetPort: 830
  type: NodePort
