---
apiVersion: v1
kind: Pod
metadata:
  name: csrx3
  # namespace: lesson1-abcdef
  labels:
    antidote_lab: "1"
    lab_instance: "1"
    podname: "csrx3"
  annotations:
    networks: '[
        { "name": "weave-lab1" },
        { "name": "weave-lab1" },
        { "name": "weave-lab1" }
    ]'
spec:
  
  # Currently tying the lab pods to the same host since I'm running into a temporary issue with multi-host weave networks
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: antidote_lab
              operator: In
              values:
              - "1"
          topologyKey: kubernetes.io/hostname
  containers:
  - name: csrx3
    image: csrx:18.1R1.9
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
    env:
    - name: CSRX_ROOT_PASSWORD
      value: Password1!
    ports:
    - containerPort: 22
    - containerPort: 830

---
kind: Service
apiVersion: v1
metadata:
  name: csrx3-service
spec:
  selector:
    antidote_lab: "1"
    lab_instance: "1"
    podname: "csrx3"
  ports:
    - name: ssh
      port: 22
      targetPort: 22
    - name: netconf
      port: 830
      targetPort: 830
  type: NodePort
