---
lessonName: Network Automation with Salt
lessonId: 30
category: configuration
lessondiagram: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-30/salt.png
tier: prod

utilities:
- name: salt1
  image: antidotelabs/salt
  ports: [22]

devices:
- name: vqfx1
  image: antidotelabs/vqfx:snap1
  ports: [8080, 830]

connections:
- a: vqfx1
  b: salt1
  subnet: 10.1.0.0/24

stages:
  - id: 1
    description: Salt Master and Minion
    labGuide: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-30/stage1/guide.md

  - id: 2
    description: Junos Proxy Minions
    labGuide: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-30/stage2/guide.md

  - id: 3
    description: Executing Junos commands in Salt
    labGuide: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-30/stage3/guide.md
