---
lessonName: End-to-End Network Testing with ToDD
lessonId: 18
category: verification
tier: ptr

utilities:
- name: todd1
  image: toddproject/todd
- name: web1
  image: nginx

devices:
- name: vqfx1
  image: antidotelabs/vqfx:snap1

connections:
- a: todd1
  b: vqfx1
  subnet: 10.12.0.0/24
- a: vqfx1
  b: web1
  subnet: 10.23.0.0/24

stages:
  - id: 1
    description: ToDD Basics
