---
apiVersion: v1
kind: Pod
metadata:
  name: vmx3
  # namespace: lesson1-abcdef
  labels:
    antidote_lab: "1"
    lab_instance: "1"
  annotations:
    networks: '[
        { "name": "ptp-mgmt" },
        { "name": "ptp23" },
        { "name": "ptp31" }
    ]'
spec:
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: antidote_lab
              operator: In
              values:
              - "1"
          topologyKey: kubernetes.io/hostname
  containers:
  - name: vmx
    image: marcelwiget/vmx-docker-light
    # image: newvmx            # REMOVE
    # imagePullPolicy: Never   # REMOVE
    # stdin: true
    # tty: true
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
    volumeMounts:
    - name: modlaunch
      mountPath: /launch.sh
    - name: host-docker
      mountPath: /var/run/docker.sock
    - name: host-myfiles
      mountPath: /u
      readOnly: true
    env:
    - name: ID
      value: "vmx1"
    - name: LICENSE
      value: "license-eval.txt"
    - name: IMAGE
      value: "junos-vmx-x86-64-18.1R1.9.qcow2"
    - name: PUBLICKEY
      value: "id_rsa.pub"
    - name: CONFIG
      value: "vmx1.conf"
    ports:
    - containerPort: 22
    - containerPort: 830
  volumes:
  - name: modlaunch
    hostPath:
      path: /home/mierdin/antidote/newvmx/launch.sh
  - name: host-docker
    hostPath:
      path: /var/run/docker.sock
  - name: host-myfiles
    hostPath:
      path: /home/mierdin/myfiles/

---
kind: Service
apiVersion: v1
metadata:
  name: vmx3-service
  # namespace: lesson1-abcdef
spec:
  selector:
    antidote_lab: "1"
    lab_instance: "1"
  ports:
    - name: ssh
      port: 22
      targetPort: 22
    - name: netconf
      port: 830
      targetPort: 830
  type: NodePort
