---
apiVersion: v1
kind: Pod
metadata:
  name: antidote-web
  labels:
    app: antidote-web
    antidote_role: infra
spec:
  containers:
  - name: guacd
    image: guacamole/guacd
    ports:
    - containerPort: 4822
  - name: guacamole
    image: guacamole/guacamole
    env:
    - name: GUACD_HOSTNAME
      value: "127.0.0.1"
    - name: GUACD_PORT
      value: "4822"
    - name: POSTGRES_HOSTNAME
      value: "db0.labs.networkreliability.engineering"
    # - name: POSTGRES_PORT
    #   value: "5432"
    - name: POSTGRES_DATABASE
      value: "guacamole_db"
    - name: POSTGRES_USER
      value: "guac_user"
    - name: POSTGRES_PASSWORD
      value: "guac"
    ports:
    - containerPort: 8080
    volumeMounts:
      - name: tomcat-users
        mountPath: /usr/local/tomcat/conf/tomcat-users.xml
  volumes:
    - name: tomcat-users
      hostPath:
        path: /home/mierdin/tomcat-users.xml

---
kind: Service
apiVersion: v1
metadata:
  name: antidote-web-service
  namespace: default
spec:
  selector:
    app: antidote-web
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
